prec:prec.cpp ../BOBHash32.h ../cuckoo_css.h ../cuckoo.h ../data.h ../definition.h ../hash_class.h ../params.h ../wcss.h
        g++ -std=c++11 -o prec prec.cpp
recall:recall.cpp ../BOBHash32.h ../cuckoo_css.h ../cuckoo.h ../data.h ../definition.h ../hash_class.h ../params.h ../wcss.h
        g++ -std=c++11 -o recall recall.cpp
clean:
        rm -f *.o prec recall

