prec:prec.cpp ../BOBHash32.h ../CSS.h ../data.h ../definition.h ../hash_class.h ../params.h ../wcss.h
	g++ -o prec prec.cpp
recall:recall.cpp ../BOBHash32.h ../CSS.h ../data.h ../definition.h ../hash_class.h ../params.h ../wcss.h
	g++ -o recall recall.cpp
clean:
	rm -f *.o prec recall
